function NumberField({ label, value, min, max, step = 1, onChange }) { return <label className="form-field"><span>{label}</span><input type="number" min={min} max={max} step={step} value={value} onChange={(e) => onChange(Number(e.target.value))} required /></label>; }
function Toggle({ label, checked, onChange }) { return <label className="checkbox-field"><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} /> {label}</label>; }

export function BroadcastSettings({ settings, setSettings, onSave, busy }) {
  const setPre = (key, value) => setSettings({ ...settings, preShow: { ...settings.preShow, [key]: value } });
  const setMid = (key, value) => setSettings({ ...settings, midRoll: { ...settings.midRoll, [key]: value } });
  const setPlayer = (key, value) => setSettings({ ...settings, player: { ...settings.player, [key]: value } });
  return <form onSubmit={onSave}>
    <section className="wm-settings-section" id="pre-show"><header><h2>Pre-show</h2></header><div className="form-grid"><NumberField label="Minimum minutes" min="1" value={settings.preShow.minMinutes} onChange={(v) => setPre("minMinutes", v)} /><NumberField label="Maximum minutes" min="1" value={settings.preShow.maxMinutes} onChange={(v) => setPre("maxMinutes", v)} /><Toggle label="Use local ads" checked={settings.preShow.useLocalAds} onChange={(v) => setPre("useLocalAds", v)} /><Toggle label="Use YouTube trailers" checked={settings.preShow.useYouTubeTrailers} onChange={(v) => setPre("useYouTubeTrailers", v)} /><Toggle label="Use countdown fallback" checked={settings.preShow.useCountdownFallback} onChange={(v) => setPre("useCountdownFallback", v)} /></div></section>
    <section className="wm-settings-section" id="breaks"><header><h2>Commercial Breaks</h2></header><div className="form-grid"><Toggle label="Enable commercial breaks" checked={settings.midRoll.enabled} onChange={(v) => setMid("enabled", v)} /><span /><NumberField label="Interval minimum (minutes)" min="5" value={settings.midRoll.intervalMinMinutes} onChange={(v) => setMid("intervalMinMinutes", v)} /><NumberField label="Interval maximum (minutes)" min="5" value={settings.midRoll.intervalMaxMinutes} onChange={(v) => setMid("intervalMaxMinutes", v)} /><NumberField label="Break duration minimum" min="1" value={settings.midRoll.durationMinMinutes} onChange={(v) => setMid("durationMinMinutes", v)} /><NumberField label="Break duration maximum" min="1" value={settings.midRoll.durationMaxMinutes} onChange={(v) => setMid("durationMaxMinutes", v)} /><NumberField label="First break after" min="0" value={settings.midRoll.firstBreakAfterMinutes} onChange={(v) => setMid("firstBreakAfterMinutes", v)} /><NumberField label="No break in last" min="0" value={settings.midRoll.noBreakLastMinutes} onChange={(v) => setMid("noBreakLastMinutes", v)} /><Toggle label="Use local ads" checked={settings.midRoll.useLocalAds} onChange={(v) => setMid("useLocalAds", v)} /><Toggle label="Use YouTube trailers" checked={settings.midRoll.useYouTubeTrailers} onChange={(v) => setMid("useYouTubeTrailers", v)} /><Toggle label="Use countdown fallback" checked={settings.midRoll.useCountdownFallback} onChange={(v) => setMid("useCountdownFallback", v)} /><Toggle label="Prevent repeats in a session" checked={settings.midRoll.preventRepeatInSession} onChange={(v) => setMid("preventRepeatInSession", v)} /><NumberField label="Default volume" min="0" max="1" step="0.05" value={settings.player.defaultVolume} onChange={(v) => setPlayer("defaultVolume", v)} /></div><div className="form-actions"><button className="primary-button" disabled={busy}>{busy ? "Saving…" : "Save broadcast settings"}</button></div></section>
  </form>;
}
