function NumberField({ label, value, min, max, step = 1, onChange }) {
  return <label className="form-field"><span>{label}</span><input type="number" min={min} max={max} step={step} value={value} onChange={(event) => onChange(Number(event.target.value))} required /></label>;
}

function Toggle({ label, checked, onChange }) {
  return <label className="checkbox-field"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /> {label}</label>;
}

export function BroadcastSettings({ settings, setSettings, onSave, busy }) {
  const setPre = (key, value) => setSettings({ ...settings, preShow: { ...settings.preShow, [key]: value } });
  const setMid = (key, value) => setSettings({ ...settings, midRoll: { ...settings.midRoll, [key]: value } });
  const setPlayer = (key, value) => setSettings({ ...settings, player: { ...settings.player, [key]: value } });
  return <form onSubmit={onSave}>
    <section className="wm-settings-section" id="pre-show"><header><h2>Pre-show</h2></header><div className="form-grid"><NumberField label="Minimum minutes" min="1" value={settings.preShow.minMinutes} onChange={(value) => setPre("minMinutes", value)} /><NumberField label="Maximum minutes" min="1" value={settings.preShow.maxMinutes} onChange={(value) => setPre("maxMinutes", value)} /><Toggle label="Use local ads" checked={settings.preShow.useLocalAds} onChange={(value) => setPre("useLocalAds", value)} /><Toggle label="Use YouTube trailers" checked={settings.preShow.useYouTubeTrailers} onChange={(value) => setPre("useYouTubeTrailers", value)} /><Toggle label="Use countdown fallback" checked={settings.preShow.useCountdownFallback} onChange={(value) => setPre("useCountdownFallback", value)} /></div></section>
    <section className="wm-settings-section" id="breaks"><header><h2>Commercial Breaks</h2></header><div className="form-grid"><Toggle label="Enable commercial breaks" checked={settings.midRoll.enabled} onChange={(value) => setMid("enabled", value)} /><span /><NumberField label="Interval minimum (minutes)" min="5" value={settings.midRoll.intervalMinMinutes} onChange={(value) => setMid("intervalMinMinutes", value)} /><NumberField label="Interval maximum (minutes)" min="5" value={settings.midRoll.intervalMaxMinutes} onChange={(value) => setMid("intervalMaxMinutes", value)} /><NumberField label="Break duration minimum" min="1" value={settings.midRoll.durationMinMinutes} onChange={(value) => setMid("durationMinMinutes", value)} /><NumberField label="Break duration maximum" min="1" value={settings.midRoll.durationMaxMinutes} onChange={(value) => setMid("durationMaxMinutes", value)} /><NumberField label="First break after" min="0" value={settings.midRoll.firstBreakAfterMinutes} onChange={(value) => setMid("firstBreakAfterMinutes", value)} /><NumberField label="No break in last" min="0" value={settings.midRoll.noBreakLastMinutes} onChange={(value) => setMid("noBreakLastMinutes", value)} /><Toggle label="Use local ads" checked={settings.midRoll.useLocalAds} onChange={(value) => setMid("useLocalAds", value)} /><Toggle label="Use YouTube trailers" checked={settings.midRoll.useYouTubeTrailers} onChange={(value) => setMid("useYouTubeTrailers", value)} /><Toggle label="Use countdown fallback" checked={settings.midRoll.useCountdownFallback} onChange={(value) => setMid("useCountdownFallback", value)} /><Toggle label="Prevent repeats in a session" checked={settings.midRoll.preventRepeatInSession} onChange={(value) => setMid("preventRepeatInSession", value)} /><NumberField label="Default volume" min="0" max="1" step="0.05" value={settings.player.defaultVolume} onChange={(value) => setPlayer("defaultVolume", value)} /></div><div className="form-actions"><button className="primary-button" disabled={busy}>{busy ? "Saving…" : "Save broadcast settings"}</button></div></section>
  </form>;
}
