import { useRef, useState } from "react";
import { Captions, X } from "lucide-react";
import { subtitleFileToVtt } from "../utils/subtitle.util";

export function SubtitleSelector({ embeddedTracks, selection, onSelection, onExternal, unavailable, secondsRemaining, onInteract, onClose }) {
  const inputRef = useRef(null); const [error, setError] = useState("");
  async function selectFile(event) { const file = event.target.files?.[0]; if (!file) return; setError(""); try { const subtitle = await subtitleFileToVtt(file); onExternal(subtitle); } catch (nextError) { setError(nextError.message); } finally { event.target.value = ""; } }
  return <section className="wm-subtitle-panel" onPointerDown={onInteract} onKeyDown={onInteract}><div className="wm-subtitle-heading"><div><Captions aria-hidden="true" /><div><h2>Subtitles</h2><p>Select a track without interrupting playback.</p></div></div><div className="wm-subtitle-dismiss"><span>Closes in 00:{String(secondsRemaining).padStart(2, "0")}</span><button type="button" aria-label="Close subtitle selector" onClick={onClose}><X aria-hidden="true" /></button></div></div><label className="form-field"><span>Active subtitle</span><select value={selection} onChange={(e) => onSelection(e.target.value)}><option value="off">Off</option>{embeddedTracks.map((track, index) => <option value={`embedded:${track.index}`} key={`${track.language}:${track.index}`}>{track.label || track.language || `Embedded track ${index + 1}`}</option>)}<option value="external">External subtitle</option></select></label><input ref={inputRef} className="sr-only" type="file" accept=".srt,.vtt,text/vtt,application/x-subrip" onChange={selectFile} /><button className="secondary-button" type="button" onClick={() => inputRef.current?.click()}>Select Subtitle File</button>{unavailable && <p className="wm-subtitle-note">Embedded subtitles are unavailable in this browser. Select an SRT or VTT file instead.</p>}{error && <p className="wm-field-error" role="alert">{error}</p>}</section>;
}
